name: ML_in_finance
channels:
  - defaults
dependencies:
  - python>=3.7
  - numpy>=1.15
  - pandas>=1.0
  - matplotlib>=3.0.0
  - scipy>=1.1.0
  - scikit-learn>=0.22
  - seaborn>=0.9.0
#  - yfinance
  - ipywidgets>=7.2.1
  - graphviz==2.50.0
  - pip>=19.0
  - pip:
    - jupyter-contrib-nbextensions>=0.5.1
    - yfinance
    - owlready2==0.46
    - rdflib==7.0.0
    - pydotplus==2.0.2
    - networkx==3.1
    - pyvis==0.3.2
  - openai
  - pypdf
  


